autolinks:
  - key_prefix: 'ACM-'
    url_template: 'https://stellarwp.atlassian.net/browse/ACM-<num>'
  - key_prefix: 'BBP-'
    url_template: 'https://stellarwp.atlassian.net/browse/BBP-<num>'
  - key_prefix: 'CG-'
    url_template: 'https://stellarwp.atlassian.net/browse/CG-<num>'
  - key_prefix: 'CO2-'
    url_template: 'https://stellarwp.atlassian.net/browse/CO2-<num>'
  - key_prefix: 'EDD-'
    url_template: 'https://stellarwp.atlassian.net/browse/EDD-<num>'
  - key_prefix: 'ELEM-'
    url_template: 'https://stellarwp.atlassian.net/browse/ELEM-<num>'
  - key_prefix: 'GF-'
    url_template: 'https://stellarwp.atlassian.net/browse/GF-<num>'
  - key_prefix: 'LCA-'
    url_template: 'https://stellarwp.atlassian.net/browse/LCA-<num>'
  - key_prefix: 'LCB-'
    url_template: 'https://stellarwp.atlassian.net/browse/LCB-<num>'
  - key_prefix: 'LCR-'
    url_template: 'https://stellarwp.atlassian.net/browse/LCR-<num>'
  - key_prefix: 'LDCC-'
    url_template: 'https://stellarwp.atlassian.net/browse/LDCC-<num>'
  - key_prefix: 'LDRFREE-'
    url_template: 'https://stellarwp.atlassian.net/browse/LDRFREE-<num>'
  - key_prefix: 'LDTECI-'
    url_template: 'https://stellarwp.atlassian.net/browse/LDTECI-<num>'
  - key_prefix: 'LI-'
    url_template: 'https://stellarwp.atlassian.net/browse/LI-<num>'
  - key_prefix: 'LEARNDASH-'
    url_template: 'https://stellarwp.atlassian.net/browse/LEARNDASH-<num>'
  - key_prefix: 'LLM-'
    url_template: 'https://stellarwp.atlassian.net/browse/LLM-<num>'
  - key_prefix: 'GIVE-'
    url_template: 'https://stellarwp.atlassian.net/browse/GIVE-<num>'
  - key_prefix: 'MEMDASH-'
    url_template: 'https://stellarwp.atlassian.net/browse/MEMDASH-<num>'
  - key_prefix: 'ML-'
    url_template: 'https://stellarwp.atlassian.net/browse/ML-<num>'
  - key_prefix: 'MP-'
    url_template: 'https://stellarwp.atlassian.net/browse/MP-<num>'
  - key_prefix: 'NOT-'
    url_template: 'https://stellarwp.atlassian.net/browse/NOT-<num>'
  - key_prefix: 'PMP-'
    url_template: 'https://stellarwp.atlassian.net/browse/PMP-<num>'
  - key_prefix: 'RC-'
    url_template: 'https://stellarwp.atlassian.net/browse/RC-<num>'
  - key_prefix: 'SAM-'
    url_template: 'https://stellarwp.atlassian.net/browse/SAM-<num>'
  - key_prefix: 'STRIPE-'
    url_template: 'https://stellarwp.atlassian.net/browse/STRIPE-<num>'
  - key_prefix: 'TC-'
    url_template: 'https://stellarwp.atlassian.net/browse/TC-<num>'
  - key_prefix: 'WOOC-'
    url_template: 'https://stellarwp.atlassian.net/browse/WOOC-<num>'
  - key_prefix: 'WPCMPLT-'
    url_template: 'https://stellarwp.atlassian.net/browse/WPCMPLT-<num>'
  - key_prefix: 'ZAP-'
    url_template: 'https://stellarwp.atlassian.net/browse/ZAP-<num>'
